import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder


def apply_preprocessing(df, plan):
    """
    Apply the preprocessing plan generated by the Preprocessing Agent.

    The agent decides WHAT preprocessing is required.
    This function decides HOW to execute that plan.
    """

    data = df.copy()

    print("\n" + "=" * 60)
    print("PREPROCESSING EXECUTOR")
    print("=" * 60)

    # ---------------------------------------------------------
    # 1. Imputation
    # ---------------------------------------------------------
    if plan["imputation"]["required"]:
        method = plan["imputation"]["method"]

        numerical_columns = data.select_dtypes(
            include=["int64", "float64", "int32", "float32"]
        ).columns

        categorical_columns = data.select_dtypes(
            include=["object", "string", "category"]
        ).columns

        if method == "median":
            for column in numerical_columns:
                data[column] = data[column].fillna(
                    data[column].median()
                )

        elif method == "mean":
            for column in numerical_columns:
                data[column] = data[column].fillna(
                    data[column].mean()
                )

        for column in categorical_columns:
            if data[column].isnull().any():
                data[column] = data[column].fillna(
                    data[column].mode()[0]
                )

        print("[OK] Imputation applied")

    else:
        print("-> Imputation skipped")

    # ---------------------------------------------------------
    # 2. Separate feature types
    # ---------------------------------------------------------
    numerical_columns = data.select_dtypes(
        include=["int64", "float64", "int32", "float32"]
    ).columns.tolist()

    categorical_columns = data.select_dtypes(
        include=["object", "string", "category"]
    ).columns.tolist()

    # Remove obvious ID columns
    id_columns = []

    for column in categorical_columns:
        if data[column].nunique() == len(data):
            id_columns.append(column)

    if id_columns:
        data = data.drop(columns=id_columns)
        categorical_columns = [
            column
            for column in categorical_columns
            if column not in id_columns
        ]

        print(f"[OK] Removed ID columns: {id_columns}")

    # ---------------------------------------------------------
    # 3. Encoding
    # ---------------------------------------------------------
    if plan["encoding"]["required"] and categorical_columns:

        method = plan["encoding"]["method"]

        if method == "one_hot":
            encoder = OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
                max_categories=30,
            )

            import numpy as np

            encoded_array = encoder.fit_transform(
                data[categorical_columns]
            ).astype(np.float32)

            encoded_columns = encoder.get_feature_names_out(
                categorical_columns
            )

            encoded_df = pd.DataFrame(
                encoded_array,
                columns=encoded_columns,
                index=data.index
            )

            data = data.drop(columns=categorical_columns)

            data = pd.concat(
                [data, encoded_df],
                axis=1
            )

            print(
                f"[OK] One-hot encoding applied to: "
                f"{categorical_columns}"
            )

    else:
        print("-> Encoding skipped")

    # ---------------------------------------------------------
    # 4. Scaling
    # ---------------------------------------------------------
    if plan["scaling"]["required"]:

        numerical_columns = data.select_dtypes(
            include=["int64", "float64", "int32", "float32"]
        ).columns.tolist()

        # Do not scale binary encoded columns
        columns_to_scale = []

        for column in numerical_columns:
            unique_values = data[column].nunique()

            if unique_values > 2:
                columns_to_scale.append(column)

        if plan["scaling"]["method"] == "standard":
            scaler = StandardScaler()

            data[columns_to_scale] = scaler.fit_transform(
                data[columns_to_scale]
            )

            print(
                f"[OK] Standard scaling applied to: "
                f"{columns_to_scale}"
            )

    else:
        print("-> Scaling skipped")

    # ---------------------------------------------------------
    # 5. Transformation
    # ---------------------------------------------------------
    if plan["transformation"]["required"]:

        method = plan["transformation"]["method"]

        if method == "log":
            for column in data.select_dtypes(
                include=["int64", "float64", "int32", "float32"]
            ).columns:

                if (data[column] >= 0).all():
                    data[column] = __import__("numpy").log1p(
                        data[column]
                    )

            print("[OK] Log transformation applied")

        else:
            print(
                f"-> Transformation method '{method}' "
                f"is not implemented yet"
            )

    else:
        print("-> Transformation skipped")

    # ---------------------------------------------------------
    # Final cleanup
    # ---------------------------------------------------------
    data = data.reset_index(drop=True)

    print("\nFinal preprocessed shape:", data.shape)

    return data